import { ClassLesson } from "@/classes/ClassLesson";

export const LESSON_IT = new ClassLesson({
    uid_intern: 1,
    uid_teacher: "HRY7JbnFftWZocKtrIB1N1YuEJw1",
    //teacher = null,
    enabled: false,
    title: "Introduction à l’informatique – Bases PC & Mobile",
    //title_normalized = "",
    subtitle: "Prends en main l’informatique et utilise PC et mobile avec confiance au quotidien.",
    //subtitle_normalized = "",
    description: "Apprends à utiliser un ordinateur et un smartphone en toute confiance : fichiers & dossiers, Internet, e-mail, cloud, PDF, sécurité, dépannage et bonnes pratiques. Un parcours simple en 3 niveaux, très orienté pratique.",
    category: ClassLesson.CATEGORY.IT,
    certified: false,
    goals: [
        "Comprendre le vocabulaire essentiel : système, application, navigateur, onglets",
        "Utiliser l’ordinateur/mobile au quotidien (clic, raccourcis, organisation des fichiers)",
        "Naviguer sur Internet et rechercher efficacement, sans tomber dans les pièges",
        "Créer et utiliser une adresse e-mail, envoyer des pièces jointes propres (PDF)",
        "Comprendre le cloud (Drive/iCloud/OneDrive), transferts mobile ↔ PC, sauvegardes",
        "Appliquer les bonnes pratiques de sécurité (2FA, mots de passe, permissions)",
        "Dépanner les problèmes courants (lenteur, stockage, réseau, apps)",
    ],
    programs: [
        "Prise en main : vocabulaire, gestes, fichiers, Internet, e-mail, sécurité de base",
        "Autonomie : cloud, transferts, stockage, PDF, scanner/impression, apps & permissions",
        "Organisation durable, partage sécurisé, sauvegardes, hygiène numérique, dépannage",
        "Dossier complet (PDF + cloud + partage propre + sauvegarde testée)",
    ],
    prerequisites: [
        "Aucun prérequis technique",
        "Savoir lire et comprendre des consignes simples",
        "Avoir un smartphone (idéal) ou un accès à un ordinateur pour pratiquer",
    ],
    target_audiences: [
       "Débutants complets (PC ou smartphone) qui veulent devenir autonomes",
        "Personnes en reconversion, recherche d’emploi, ou besoin administratif",
        "Étudiants/stagiaires qui veulent de bonnes bases numériques",
        "Toute personne souhaitant mieux organiser ses fichiers et sécuriser ses comptes",
    ],
    materials: [
        "Un smartphone (Android ou iPhone) pour pratiquer les transferts / scans.",
        "Un ordinateur (Windows ou Mac) pour les fichiers & dossiers.",
        "Une adresse e-mail active (ou on la crée ensemble).",
        "Optionnel : clé USB ou disque externe pour une copie locale.",
    ],
    tags:[
        {title:"🎯 Très orienté pratique", subtitle:"Des exercices “vraie vie” (documents, e-mail, PDF, cloud, sécurité)."},
        {title:"🧩 3 niveaux progressifs",subtitle:"Débutant → Intermédiaire → Compétent, avec quiz à chaque niveau."},
        {title:"🔐 Réflexes de sécurité",subtitle:"Mots de passe, 2FA, permissions, liens suspects, mises à jour."},
    ],
    notes: [],
    //photo_url = "",
    //status: ClassLesson.STATUS.OPEN,
    //translate = {},
    //translates = [],
    //created_time = new Date(),
    //last_edit_time = new Date(),
});
export const LESSON_WORD = new ClassLesson({
    uid_intern: 2,
    uid_teacher: "HRY7JbnFftWZocKtrIB1N1YuEJw1",
    //teacher = null,
    enabled: false,
    title: "Word – Documents professionnels & mise en page",
    //title_normalized = "",
    subtitle: "Les bases essentielles pour créer des documents Word professionnels et bien structurés.",
    //subtitle_normalized = "",
    description: "Apprends à créer des documents propres et professionnels : mise en forme, styles, mise en page, tableaux, images, export PDF et bonnes pratiques pour gagner du temps.",
    category: ClassLesson.CATEGORY.OFFICE,
    certified: true,
    goals: [
        "Comprendre l’interface de Word et les bases de la mise en forme",
        "Structurer un document avec titres, styles et sections",
        "Mettre en page correctement (marges, en-têtes/pieds, numérotation)",
        "Insérer et mettre en forme tableaux, images et éléments graphiques",
        "Exporter un document professionnel (PDF) et préparer l’impression",
    ],
    programs: [
        "Découvrir Word & prise en main de l’interface",
        "Mise en forme du texte et mise en page",
        "Styles, titres et structure du document",
        "Insertion d’images, tableaux et éléments",
        "En-têtes/pieds, numérotation, sections",
        "Mini-projet : CV / lettre / rapport + export PDF",
    ],
    prerequisites: [
        "Savoir utiliser un ordinateur (souris, clavier, navigation simple)",
        "Aucun prérequis sur Word n’est nécessaire",
    ],
    target_audiences: [
        "Personnes en reconversion ou en recherche d’emploi",
        "Professionnels souhaitant produire des documents plus propres et rapides",
        "Étudiants ou stagiaires qui rédigent rapports, CV ou documents académiques",
    ],
    materials: [
        "Un ordinateur (Windows ou Mac) pour les fichiers & dossiers.",
        "Le logiciel Microsoft Word",
    ],
    notes: [],
    tags: [],
    //photo_url = "",
    //status: ClassLesson.STATUS.OPEN,
    //translate = {},
    //translates = [],
    //created_time = new Date(),
    //last_edit_time = new Date(),
});